name: Flutter analyze

on: 
  workflow_call:
    secrets:
      GIT_TOKEN:
        required: true

jobs:
  analyze:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Configuring flutter environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.2'
          channel: 'stable'  
      - name: "Bootstrap Main Workspace"
        run: flutter packages get
      - name: "Bootstrap Sample"
        run: |
          touch sample/.env
          flutter pub get && flutter pub get sample
      - name: "Flutter Analyze"
        run: flutter analyze .
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
