name: Pull request check

on: 
  workflow_call:
    inputs:
      SSH_PRIVATE_KEY_CORE:
        required: true
      SSH_PRIVATE_KEY_DS:
        required: true
      GIT_TOKEN:
        required: true

jobs:
  analyze:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configuring flutter environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.2'
          channel: 'stable'  
      - uses: webfactory/ssh-agent@v0.5.4
        with:
            ssh-private-key: |
                  ${{ inputs.SSH_PRIVATE_KEY_CORE }}
                  ${{ inputs.SSH_PRIVATE_KEY_DS }}
      - name: "Bootstrap Main Workspace"
        run: flutter packages get
      - name: "Bootstrap Sample"
        run: |
          touch sample/.env
          flutter pub get && flutter pub get sample
      - name: "Flutter Analyze"
        run: flutter analyze .
        env:
          GITHUB_TOKEN: ${{ inputs.GIT_TOKEN }}
      
  format:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configuring flutter environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.2'
          channel: 'stable'  
      - uses: webfactory/ssh-agent@v0.5.4
        with:
            ssh-private-key: |
                  ${{ inputs.SSH_PRIVATE_KEY_CORE }}
                  ${{ inputs.SSH_PRIVATE_KEY_DS }}
      - name: "Bootstrap Main Workspace"
        run: flutter packages get
      - name: "Bootstrap Sample"
        run: |
          touch sample/.env
          flutter packages get
      - name: "Flutter Analyze"
        run: flutter format . --set-exit-if-changed 
        env:
          GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}

  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configuring flutter environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.2'
          channel: 'stable'  
      - uses: webfactory/ssh-agent@v0.5.4
        with:
            ssh-private-key: |
                  ${{ inputs.SSH_PRIVATE_KEY_CORE }}
                  ${{ inputs.SSH_PRIVATE_KEY_DS }}
      - name: "Bootstrap Main Workspace"
        run: flutter packages get
      - name: "Bootstrap Sample"
        run: |
          touch sample/.env
          flutter packages get
      - name: "Flutter Analyze"
        run: flutter test . 
        env:
          GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
    